// Object: PlayerAbilityCategory
// RuntimeId: 60038
// TypeInfo: 0x0000000144DF7760

namespace DiceShooterShared {
    enum PlayerAbilityCategory {
        PlayerAbilityCategory_Primary = 0,
        PlayerAbilityCategory_Middle = 1,
        PlayerAbilityCategory_Left = 2,
        PlayerAbilityCategory_Right = 3,
        PlayerAbilityCategory_AltFire1 = 4,
        PlayerAbilityCategory_AltFire2 = 5,
        PlayerAbilityCategory_AltFire3 = 6,
        PlayerAbilityCategory_Up = 7,
        PlayerAbilityCategory_Down = 8,
        PlayerAbilityCategory_Passive = 9,
        PlayerAbilityCategory_Evade = 10,
        PlayerAbilityCategory_HeroMenu = 11,
        PlayerAbilityCategory_Legendary = 12,
        PlayerAbilityCategory_Pickup = 13,
        PlayerAbilityCategory_Extra1 = 14,
        PlayerAbilityCategory_Extra2 = 15,
        PlayerAbilityCategory_Extra3 = 16,
        PlayerAbilityCategory_Extra4 = 17,
        PlayerAbilityCategory_LLeft = 18,
        PlayerAbilityCategory_LRight = 19,
        PlayerAbilityCategory_LUp = 20,
        PlayerAbilityCategory_LDown = 21,
        PlayerAbilityCategory_Emote = 22,
        PlayerAbilityCategory_Emote1 = 23,
        PlayerAbilityCategory_Emote2 = 24,
        PlayerAbilityCategory_Emote3 = 25,
        PlayerAbilityCategory_VictoryPose = 26,
        PlayerAbilityCategory_Bottom = 27,
        PlayerAbilityCategory_CommoRose = 28,
        PlayerAbilityCategory_VOWheel = 29,
        PlayerAbilityCategory_Count = 30,
        PlayerAbilityCategory_Invalid = 31
    };
}