// Object: RigidBodyCollisionLayer
// RuntimeId: 13744
// TypeInfo: 0x0000000144F0D560

namespace Physics {
    enum RigidBodyCollisionLayer {
        RigidBodyCollisionLayer_Invalid = 0,
        RigidBodyCollisionLayer_StaticLayer = 1,
        RigidBodyCollisionLayer_DynamicLayer = 2,
        RigidBodyCollisionLayer_PlayerCollisionLayer = 3,
        RigidBodyCollisionLayer_AICollisionLayer = 4,
        RigidBodyCollisionLayer_KeyframeLayer = 5,
        RigidBodyCollisionLayer_DebrisLayer = 6,
        RigidBodyCollisionLayer_FastDebrisLayer = 7,
        RigidBodyCollisionLayer_OnlyStaticCollisionLayer = 8,
        RigidBodyCollisionLayer_RagdollLayer = 9,
        RigidBodyCollisionLayer_NoCollisionLayer = 10,
        RigidBodyCollisionLayer_WaterLayer = 11,
        RigidBodyCollisionLayer_BangerLayer = 12,
        RigidBodyCollisionLayer_NoVehicleCollisionLayer = 13,
        RigidBodyCollisionLayer_CharacterLayer = 14,
        RigidBodyCollisionLayer_DynamicNoCharacterCollisionLayer = 15,
        RigidBodyCollisionLayer_OnlyVehicleCollisionLayer = 16,
        RigidBodyCollisionLayer_TerrainLayer = 17,
        RigidBodyCollisionLayer_OnlyTerrainCollionLayer = 18,
        RigidBodyCollisionLayer_CharacterCollisionGeometryLayer = 19,
        RigidBodyCollisionLayer_AiCollisionBodyLayer = 20,
        RigidBodyCollisionLayer_CameraCollisionLayer = 21,
        RigidBodyCollisionLayer_OnlyStaticCameraCollisionLayer = 22,
        RigidBodyCollisionLayer_KeyframedCollisionBodyLayer = 23,
        RigidBodyCollisionLayer_VehicleLayer = 24,
        RigidBodyCollisionLayer_VehicleAndCharacterCollisionLayer = 25,
        RigidBodyCollisionLayer_OnlyStaticDynamicTerrainCollisionLayer = 26,
        RigidBodyCollisionLayer_SimpleTerrainLayer = 27,
        RigidBodyCollisionLayer_OnlyStaticAndTerrainLayer = 28,
        RigidBodyCollisionLayer_NoSpectatorStaticCollisionLayer = 29,
        RigidBodyCollisionLayer_SpectatorCameraCollisionLayer = 30,
        RigidBodyCollisionLayer_NoWaterCollisionLayer = 31,
        RigidBodyCollisionLayer_Size = 32
    };
}