// Object: AutoPlayerSettings
// ClassId: 4958
// RuntimeId: 3022
// TypeInfo: 0x0000000144BEC990
#include "../Core/SystemSettings.h"
#include "../Global/Float32.h"
#include "../Global/Boolean.h"
#include "../Global/Int32.h"
#include "../Global/Uint32.h"
#include "../Global/CString.h"

#pragma pack(push, 8)
namespace AutoPlayers {
    class AutoPlayerSettings : public Core::SystemSettings {
        Float32 AFKTakeover; // 0x20
        Int32 PlayerCount; // 0x24
        Int32 ForcedServerAutoPlayerCount; // 0x28
        Int32 ForceFillTeam1; // 0x2C
        Int32 ForceFillTeam2; // 0x30
        Float32 RespawnDelay; // 0x34
        Float32 InitialRespawnDelay; // 0x38
        Float32 ClientJoinDelay; // 0x3C
        Int32 RoundTimeout; // 0x40
        Int32 SquadMembers; // 0x44
        Int32 PickupItemsSecondaryObjectiveAttemptIntervalSeconds; // 0x48
        Float32 PlannerTerrainVerticalCutoff; // 0x4C
        Float32 PlannerConnectionCutoff; // 0x50
        Float32 PlannerMaxNodesSearchRadius; // 0x54
        Float32 PlannerLinkEndArrivalRange; // 0x58
        Float32 InputScaleYaw; // 0x5C
        Float32 InputScalePitch; // 0x60
        Float32 InputScaleClient; // 0x64
        Float32 InputOverrideYaw; // 0x68
        Float32 InputOverridePitch; // 0x6C
        Float32 AimAcceleration; // 0x70
        Float32 AimLapTime; // 0x74
        Float32 LofTimeoutS; // 0x78
        Float32 LofReactionTimeS; // 0x7C
        Int32 ForceKit; // 0x80
        Float32 SquadSpawnProbability; // 0x84
        Float32 KitChangeProbability; // 0x88
        Float32 UseDefaultUnlocksProbability; // 0x8C
        Float32 WeaponSwapIntervalS; // 0x90
        Float32 WeaponSwapPrimaryProbability; // 0x94
        Int32 VehicleBailTime; // 0x98
        Float32 JumpIfStuckTimeSeconds; // 0x9C
        Float32 JumpCooldownSeconds; // 0xA0
        Float32 PatrolPositionCooldownSeconds; // 0xA4
        Float32 ForcedFireTimeMaxS; // 0xA8
        Float32 ForcedFireTimeMinS; // 0xAC
        Float32 ForcedFireVehicleTimeScale; // 0xB0
        Float32 ExitVehicleWhenStuckTimeout; // 0xB4
        Float32 MinDistanceForVehicleUTurn; // 0xB8
        Int32 MinAirplaneBailOutTime; // 0xBC
        Int32 MaxAirplaneBailOutTime; // 0xC0
        Float32 LoginRate; // 0xC4
        Float32 SpawnRate; // 0xC8
        Int32 MaxSpawnsPerUpdate; // 0xCC
        Float32 Variance; // 0xD0
        Int32 AirplaneExitInput; // 0xD4
        Float32 SecondaryObjectiveGenerationMinSeconds; // 0xD8
        Float32 SecondaryObjectiveGenerationMaxSeconds; // 0xDC
        Float32 EnterVehicleCooldownSeconds; // 0xE0
        Float32 EnterVehicleProbability; // 0xE4
        Float32 EnterVehicleSearchRadius; // 0xE8
        Float32 SecondaryObjectiveTimeoutSeconds; // 0xEC
        Float32 FortificationProbability; // 0xF0
        Float32 FortificationSearchRadius; // 0xF4
        Float32 RepathCooldownSeconds; // 0xF8
        Float32 UnStuckVehicleActionsTriggerTimeSeconds; // 0xFC
        Float32 UnstuckMinimalMoveDistance; // 0x100
        Float32 UnstuckMinimalMoveSuicideTimeout; // 0x104
        Float32 FallenBelowSuicideTimeout; // 0x108
        Float32 NavigationPositionToleranceMeters; // 0x10C
        Float32 StuckEscapeProcedureSensorLength; // 0x110
        Float32 StuckEscapeProcedurePIFraction; // 0x114
        Float32 StuckEscapeProcedureEscapeDistance; // 0x118
        Float32 StuckEscapeProcedureActivationSeconds; // 0x11C
        Float32 StuckEscapeProcedureUpdateInterval; // 0x120
        Float32 StuckEscapeProcedureTimeoutSeconds; // 0x124
        Float32 UnStuckActionsTriggerTimeSeconds; // 0x128
        Float32 UnStuckActionsTriggerCooldown; // 0x12C
        Int32 StuckEscapeProcedureRetries; // 0x130
        Float32 PrimaryInteractionSearchRadius; // 0x134
        Float32 SecondaryInteractionsProbability; // 0x138
        Float32 SecondaryInteractionsSearchRadius; // 0x13C
        Float32 SecondaryObjectivePickupItemsSearchRadius; // 0x140
        Float32 SecondaryObjectivePickupItemsInteractOrActionRadius; // 0x144
        Float32 SecondaryReviveSearchDistance; // 0x148
        Float32 ExpectedTravelTimeDistanceScale; // 0x14C
        Float32 ExpectedTravelTimeBase; // 0x150
        Float32 InteractAreaTime; // 0x154
        Int32 DebugHighlightObjectiveType; // 0x158
        Float32 SeekAndDestroyMinRadius; // 0x15C
        Float32 SeekAndDestroyMaxRadius; // 0x160
        Float32 ForceRepathIfTooFarFromWaypointMeters; // 0x164
        Float32 WaypointMinimumProgressMeters; // 0x168
        Float32 AimNoiseScale; // 0x16C
        Float32 VehicleAimNoiseScale; // 0x170
        Float32 TargetMinSwitchTimeS; // 0x174
        Float32 MaxTargetEngagingDistanceScale; // 0x178
        Float32 RandomPathSpreadRadius; // 0x17C
        Float32 RandomPathSpreadCenterDistance; // 0x180
        Float32 UpdateTargetCooldown; // 0x184
        Float32 ForcedTargetTimeoutSeconds; // 0x188
        Float32 ActionObjectiveDefaultTime; // 0x18C
        Float32 ActionGadgetProbability; // 0x190
        Float32 ActionGadgetInteractableSearchRadius; // 0x194
        Float32 FollowTargetPositionCheckCooldown; // 0x198
        Float32 NotAliveAssertTime; // 0x19C
        Float32 TimeOnPathToleranceSeconds; // 0x1A0
        Float32 SwimmingSuicideTimeout; // 0x1A4
        Float32 LofPredictionTime; // 0x1A8
        Float32 TargetTrackerFieldOfViewDegrees; // 0x1AC
        Uint32 UpdateTargetPerFrameCap; // 0x1B0
        char pad_0x1B4[0x4];
        CString ReplayTelemetryFile; // 0x1B8
        CString ReplayTelemetryFileFormat; // 0x1C0
        Float32 ReplayTelemetryAdjustTimePadding; // 0x1C8
        Float32 AimSmoothingTime; // 0x1CC
        Float32 AimScaleGamePad; // 0x1D0
        Float32 AimScaleMouse; // 0x1D4
        Float32 AimScaleServer; // 0x1D8
        Float32 AimScaleAirplane; // 0x1DC
        Float32 AimScaleVehicle; // 0x1E0
        Float32 AimScaleZoomClient; // 0x1E4
        Float32 AimScaleZoomServer; // 0x1E8
        Float32 AimScaleCombat; // 0x1EC
        Float32 DebugWindowPositionScaleOffsetX; // 0x1F0
        Float32 DebugWindowPositionScaleOffsetY; // 0x1F4
        Int32 DebugWindowWidth; // 0x1F8
        Int32 DebugWindowHeight; // 0x1FC
        Float32 EvasiveManeuversJumpProbability; // 0x200
        Float32 EvasiveManeuversCrouchProbability; // 0x204
        Float32 EvasiveManeuversCrouchDuration; // 0x208
        Float32 EvasiveManeuversInvertStrafeDurationMax; // 0x20C
        Float32 EvasiveManeuversInvertStrafeDurationMin; // 0x210
        Float32 SprintCooldown; // 0x214
        Float32 ShortestLofRange; // 0x218
        Float32 TargetBlacklistTimeoutS; // 0x21C
        Float32 TargetBlacklistClearTimerS; // 0x220
        Boolean ServerEnabled; // 0x224
        Boolean ClientEnabled; // 0x225
        Boolean AllowClientTakeOver; // 0x226
        Boolean ForceServerControl; // 0x227
        Boolean ClientOwnsObjectiveControl; // 0x228
        Boolean DebugDrawEnabled; // 0x229
        Boolean DebugDrawWaypoints; // 0x22A
        Boolean DebugDrawClientDetails; // 0x22B
        Boolean DebugDrawCombatDetails; // 0x22C
        Boolean AllowAddAutoFillPlayers; // 0x22D
        Boolean AllowRemoveAutoFillPlayers; // 0x22E
        Boolean AllowVehicleSpawn; // 0x22F
        Boolean ForceDisableVehicleSpawn; // 0x230
        Boolean AllowClientVehicleSpawn; // 0x231
        Boolean AllowFirstClientInitialVehicleSpawn; // 0x232
        Boolean AllowVehicleTarget; // 0x233
        Boolean AllowOnlyVehiclesTargetVehicles; // 0x234
        Boolean ControlConnectionlessPlayers; // 0x235
        Boolean AllowRespawn; // 0x236
        Boolean UseTelemetryBasedPlanner; // 0x237
        Boolean DebugTelemetryBasedPlanner; // 0x238
        Boolean UseFadeOverride; // 0x239
        Boolean InputForceMouse; // 0x23A
        Boolean UseInputOverrideYawPitch; // 0x23B
        Boolean UseSeekAndDestroy; // 0x23C
        Boolean AllowTeleport; // 0x23D
        Boolean ForceAllowAllTeleports; // 0x23E
        Boolean DebugDrawTeleports; // 0x23F
        Boolean UpdateAI; // 0x240
        Boolean DebugDrawClientOnly; // 0x241
        Boolean DebugDrawClientRealmOnly; // 0x242
        Boolean AllowMoveOutsideCombatArea; // 0x243
        Boolean AllowSpawnOutsideCombatArea; // 0x244
        Boolean AllowVehicleSpawnOutsideCombatArea; // 0x245
        Boolean AllowVehicleSpawnOnly; // 0x246
        Boolean DebugDrawPrettyPath; // 0x247
        Boolean DebugDrawUseWaypointsAlpha; // 0x248
        Boolean DebugDrawUseDetailedCorridor; // 0x249
        Boolean DebugDrawInvalidMoveIntention; // 0x24A
        Boolean DebugSpam; // 0x24B
        Boolean ServerPlayersIgnoreClientPlayers; // 0x24C
        Boolean IgnoreHumanPlayers; // 0x24D
        Boolean OpportunisticInteract; // 0x24E
        Boolean AllowMedicRevive; // 0x24F
        Boolean AllowPickupItems; // 0x250
        Boolean DebugDrawObjectives; // 0x251
        Boolean DebugDrawObjectiveAlways; // 0x252
        Boolean Wallhack; // 0x253
        Boolean CombatUseGrenades; // 0x254
        Boolean CombatUseProne; // 0x255
        Boolean CombatUseMelee; // 0x256
        Boolean UseCrouch; // 0x257
        Boolean CombatUseZoom; // 0x258
        Boolean AllowPrimaryWeaponForcedFire; // 0x259
        Boolean AllowVehicleForcedFire; // 0x25A
        Boolean AllowEnterVehicle; // 0x25B
        Boolean PrintClientInput; // 0x25C
        Boolean AllowPrimaryObjective; // 0x25D
        Boolean AllowSecondaryObjectivesWhilePassive; // 0x25E
        Boolean AllowSecondaryObjectivesWhileDefensive; // 0x25F
        Boolean AllowPathfinding; // 0x260
        Boolean ForcePassiveMode; // 0x261
        Boolean ForcePrimaryObjectiveDefensiveMode; // 0x262
        Boolean ForcePrimaryObjectiveAggressiveMode; // 0x263
        Boolean ForceSecondaryObjectiveDefensiveMode; // 0x264
        Boolean ForceSecondaryObjectiveAggressiveMode; // 0x265
        Boolean ClientJesusMode; // 0x266
        Boolean ClientUnlimitedMags; // 0x267
        Boolean AllowFortifications; // 0x268
        Boolean UseUXRPlayerNames; // 0x269
        Boolean AllowStuckEscapeProcedure; // 0x26A
        Boolean ExitStuckEscapeProcedureOnVisualCheck; // 0x26B
        Boolean DebugDrawUnstuck; // 0x26C
        Boolean AllowSuicide; // 0x26D
        Boolean AllowRandomBehavior; // 0x26E
        Boolean AllowSecondaryInteractions; // 0x26F
        Boolean SecondaryObjectiveJesusMode; // 0x270
        Boolean DebugDrawNavigationDetails; // 0x271
        Boolean DebugDrawNavigationProgressDetails; // 0x272
        Boolean DebugDrawCustomInput; // 0x273
        Boolean DebugDrawInputDetails; // 0x274
        Boolean DebugDrawAimNoise; // 0x275
        Boolean AllowRandomPathSpread; // 0x276
        Boolean ForceUseRandomPathSpread; // 0x277
        Boolean DebugDrawPlayersNamesAndIds; // 0x278
        Boolean DebugDrawHighlightClients; // 0x279
        Boolean VerboseLogging; // 0x27A
        Boolean AllowActionGadget; // 0x27B
        Boolean PreferFPSCamera; // 0x27C
        Boolean CheckWaterDepthForIntermediatePositions; // 0x27D
        Boolean DebugDrawCombatRaycastHitPoints; // 0x27E
        Boolean DebugDrawAimTransforms; // 0x27F
        Boolean TargetLock; // 0x280
        Boolean PickRandomVehicleOnSecondaryObjective; // 0x281
        Boolean NeverExitVehicleAfterEntering; // 0x282
        Boolean AbandonVehicleWhenOutOfFuel; // 0x283
        Boolean ReplayTelemetryAdjustTime; // 0x284
        Boolean DebugDrawWeaponDetails; // 0x285
        Boolean DebugDrawExtensiveClientDetails; // 0x286
        Boolean AllowSecondaryObjectivesOutsideObjectiveRestrictedArea; // 0x287
    }; // 0x288
    static_assert(sizeof(AutoPlayerSettings) == 0x288);
}
#pragma pack(pop)