// Object: AutoGeneratedBundle
// RuntimeId: 30338
// TypeInfo: 0x0000000144E85740
#pragma pack(push, 8)
namespace GameShared {
    struct AutoGeneratedBundle {
        char pad_0x0[0x38];
    }; // 0x38
    static_assert(sizeof(AutoGeneratedBundle) == 0x38);
}
#pragma pack(pop)