// Object: UIMessageType
// RuntimeId: 54230
// TypeInfo: 0x0000000144E91020

namespace GameShared {
    enum UIMessageType {
        UIMessageType_Text = 0,
        UIMessageType_EnemyTank = 1,
        UIMessageType_EnemyCar = 2,
        UIMessageType_EnemyBoat = 3,
        UIMessageType_EnemyHelicopter = 4,
        UIMessageType_EnemyInfantry = 5,
        UIMessageType_EnemyActivity = 6,
        UIMessageType_EnemyC4 = 7,
        UIMessageType_EnemyATMine = 8,
        UIMessageType_ChatGo = 9,
        UIMessageType_ChatFollowMe = 10,
        UIMessageType_ChatNeedBackup = 11,
        UIMessageType_ChatNeedPickup = 12,
        UIMessageType_ChatNeedAmmo = 13,
        UIMessageType_ChatNeedMedic = 14,
        UIMessageType_ChatYes = 15,
        UIMessageType_ChatNo = 16,
        UIMessageType_ChatThanks = 17,
        UIMessageType_ChatSorry = 18,
        UIMessageType_ChatNeedRepair = 19,
        UIMessageType_ChatGetIn = 20,
        UIMessageType_ChatGetOut = 21,
        UIMessageType_ChatDropMeOff = 22,
        UIMessageType_OrderDefendBase = 23,
        UIMessageType_OrderAttackBase = 24,
        UIMessageType_OrderMoveToPos = 25,
        UIMessageType_JoinedSquad = 26,
        UIMessageType_LeftSquad = 27,
        UIMessageType_RequestSquad = 28,
        UIMessageType_InviteSquad = 29,
        UIMessageType_KickSquad = 30,
        UIMessageType_LeaderPromoted = 31,
        UIMessageType_Connected = 32,
        UIMessageType_Disconnected = 33,
        UIMessageType_Killed = 34,
        UIMessageType_Died = 35
    };
}